ALTER TABLE servers
ADD COLUMN IF NOT EXISTS port INT DEFAULT 22 AFTER hostname,
ADD COLUMN IF NOT EXISTS ssh_user VARCHAR(255) AFTER port,
ADD COLUMN IF NOT EXISTS ssh_password VARCHAR(255) AFTER ssh_user,
ADD COLUMN IF NOT EXISTS ssh_status ENUM('success', 'fail') DEFAULT 'fail' AFTER ssh_password;
