ALTER TABLE servers
    ADD COLUMN IF NOT EXISTS target_type VARCHAR(30) NOT NULL DEFAULT 'other',
    ADD COLUMN IF NOT EXISTS environment VARCHAR(30) NOT NULL DEFAULT 'production',
    ADD COLUMN IF NOT EXISTS criticality VARCHAR(20) NOT NULL DEFAULT 'medium',
    ADD COLUMN IF NOT EXISTS tags VARCHAR(255) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS collection_method VARCHAR(30) NOT NULL DEFAULT 'ssh';
