<?php
namespace MSM;

final class CheckCatalog
{
    public static function all(): array
    {
        return [
            [
                'name' => 'Supervision',
                'unit' => 'msm-check-servers',
                'description' => 'MSM server supervision check',
                'timer_description' => 'Run MSM server supervision check every minute',
                'settings_category' => 'supervision',
                'interval_key' => 'check_interval_minutes',
                'interval_unit' => 'minutes',
                'cron' => '* * * * *',
                'log_stale_after_minutes' => 5,
                'on_boot' => '1min',
                'on_active' => '1min',
                'script' => 'check-servers.php',
                'log' => 'check-servers.log',
            ],
            [
                'name' => 'Patch Management',
                'unit' => 'msm-check-patches',
                'description' => 'MSM patch management check',
                'timer_description' => 'Run MSM patch management check every 10 minutes',
                'settings_category' => 'patch_management',
                'interval_key' => 'check_interval_hours',
                'interval_unit' => 'hours',
                'cron' => '*/10 * * * *',
                'log_stale_after_minutes' => 30,
                'on_boot' => '5min',
                'on_active' => '10min',
                'script' => 'check-patches.php',
                'log' => 'check-patches.log',
            ],
            [
                'name' => 'Cycle de vie OS',
                'unit' => 'msm-check-os-lifecycle',
                'description' => 'MSM OS lifecycle check',
                'timer_description' => 'Run MSM OS lifecycle check hourly',
                'settings_category' => 'os_lifecycle',
                'interval_key' => 'check_interval_hours',
                'interval_unit' => 'hours',
                'cron' => '15 * * * *',
                'log_stale_after_minutes' => 180,
                'on_boot' => '10min',
                'on_active' => '1h',
                'script' => 'check-os-lifecycle.php',
                'log' => 'check-os-lifecycle.log',
            ],
            [
                'name' => 'Securite',
                'unit' => 'msm-check-security',
                'description' => 'MSM security check',
                'timer_description' => 'Run MSM security check hourly',
                'settings_category' => 'security',
                'interval_key' => 'check_interval_hours',
                'interval_unit' => 'hours',
                'cron' => '30 * * * *',
                'log_stale_after_minutes' => 180,
                'on_boot' => '15min',
                'on_active' => '1h',
                'script' => 'check-security.php',
                'log' => 'check-security.log',
            ],
            [
                'name' => 'Sante materielle',
                'unit' => 'msm-check-hardware-health',
                'description' => 'MSM hardware health check',
                'timer_description' => 'Run MSM hardware health check every 5 minutes',
                'settings_category' => 'hardware_health',
                'interval_key' => 'check_interval_minutes',
                'interval_unit' => 'minutes',
                'cron' => '*/5 * * * *',
                'log_stale_after_minutes' => 20,
                'on_boot' => '5min',
                'on_active' => '5min',
                'script' => 'check-hardware-health.php',
                'log' => 'check-hardware-health.log',
            ],
            [
                'name' => 'Home Assistant',
                'unit' => 'msm-check-home-assistant',
                'description' => 'MSM Home Assistant check',
                'timer_description' => 'Run MSM Home Assistant check every 15 minutes',
                'settings_category' => 'home_assistant',
                'interval_key' => 'check_interval_minutes',
                'interval_unit' => 'minutes',
                'cron' => '*/15 * * * *',
                'log_stale_after_minutes' => 45,
                'on_boot' => '7min',
                'on_active' => '15min',
                'script' => 'check-home-assistant.php',
                'log' => 'check-home-assistant.log',
            ],
            [
                'name' => 'Alerting',
                'unit' => 'msm-check-alerts',
                'description' => 'MSM alerting evaluation',
                'timer_description' => 'Run MSM alerting evaluation every 5 minutes',
                'settings_category' => 'alerting',
                'interval_key' => 'check_interval_minutes',
                'interval_unit' => 'minutes',
                'cron' => '*/5 * * * *',
                'log_stale_after_minutes' => 20,
                'on_boot' => '2min',
                'on_active' => '5min',
                'script' => 'check-alerts.php',
                'log' => 'check-alerts.log',
            ],
        ];
    }
}
